### ISSUE TITLE
PERMANENT FEATURE FREEZE

### ISSUE THREAD

**Issue by Zumorica** [Moe-Team/MysteryOnline#150]
Sister issue to #151 
MO (Python) isn't accepting any new feature PRs from this point forward.
Until we switch to a new client (written in C#) we will only accept bug/crash fixes.

**Comment by Unbancho** [comment]
no

**Comment by Zumorica** [comment]
I will step back on this one at least, and say we take this feature freeze with a grain of salt.
New features is fine, but I'd honestly discourage everyone from actually contributing new stuff until the rewrite is done.

**Comment by Zumorica** [comment]
I will step back on this one at least, and say we take this feature freeze with a grain of salt.
New features is fine, but I'd honestly discourage everyone from actually contributing new stuff until the rewrite is done.

**Comment by Zumorica** [comment]
I will step back on this one at least, and say we take this feature freeze with a grain of salt.
New features is fine, but I'd honestly discourage everyone from actually contributing new stuff until the rewrite is done.

**Comment by Zumorica** [comment]
Closing for now.
