### ISSUE TITLE
A better font that allows more characters, like Kanji

### ISSUE THREAD

**Issue by Cascascap** [Moe-Team/MysteryOnline#17]

**Comment by PantherXoXtacO** [comment]
I've been testing out some fonts for MO that support kanji (and are free)
[The few i tested](https://www.dropbox.com/sh/tk037bs6jynwd1x/AAB9i9sI4EeqrtPY4mBc68Wna?dl=0)

**Comment by Weeping-Cat** [comment]
I like Osaka 01

**Comment by PantherXoXtacO** [comment]
Ok, the one i'll push will be Osaka 01.
I'll also make it that changing the font will be easy for users.
And I'll separate the label font from the input font for more customizability.
