### ISSUE TITLE
Music List Enhancement

### ISSUE THREAD

**Issue by Aecheritt** [Moe-Team/MysteryOnline#23]
- Tooltip for long titles (though those titles need to be centered because you can't exactly tell whether it's a very short title or just cut, like in this screenshot):
https://i.imgur.com/C2LOlHC.png
Secret Base - Left Behind by the Adults~ is supposed to be the title but we can only see "Adults~" in this screenshot, there are many songs like those.

- The songs highlight when your mouse moves over them, it would be nice, if it's possible.

**Comment by MurdockHM** [comment]
Improved track title display so tooltips are unnecessary. As for the highlighting, I might do something about it in the future, but for now, I don't think it's necessary either and would only be more trouble than worth.
