### ISSUE TITLE
Music List Enhancement #2

### ISSUE THREAD

**Issue by Aecheritt** [Moe-Team/MysteryOnline#25]
Queue system:
- If a song is put in the music thing, then another one is put, it won't stop the currently playing song unless it has played once and looped. Queue only happens when the currently playing song has not finished once already. 
- Skip button, for queue, that is greyed out when there is no currently playing song, also means that there should be a way to see the whole playlist.
- Maybe like in Discord, unless it's the one who played the song, you can only stop a song through vote if it hasn't looped once already (?)

**Comment by MurdockHM** [comment]
After hours of intense discussion, we've decided this would create more trouble than it's worth. Maybe we could implement something similar, but that's something for the distant future most likely.

**Comment by Aecheritt** [comment]
Oh right I had a github account, and for once I check my mails too, too bad
