### ISSUE TITLE
Mirror issues

### ISSUE THREAD

**Issue by Aecheritt** [Moe-Team/MysteryOnline#3]
~~1. You can't mirror a CG (if that CG is written in the .ini file, and not a CG alone like prior to the implementation of CGs)~~

2. Mirroring on the same sublocation with the same character and the same emote as someone else makes them both mirror, independently from the other user's desire, which is pretty funny and should be a feature

~~3. When you mirror a sprite then change emote while keeping the mirror option, the preview will appear normally, as if the option wasn't ticked, but once you actually type, it works. The preview is the only part that is bugged, including the tooltip preview.~~

**Comment by MurdockHM** [comment]
> [...] which is pretty funny and should be a feature

Ask and you shall receive.
