### ISSUE TITLE
Crash on retrying to connect with changed name and problems with empty username

### ISSUE THREAD

**Issue by Cascascap** [Moe-Team/MysteryOnline#6]
If your nickname is in use and you try to connect with another one, you will get a script error and MO will crash.

Additionally if you never put an username and leave the textbox empty, it will load forever.

log:
[kivy_18-01-03_17.txt](https://github.com/Moe-Team/MysteryOnline/files/1602097/kivy_18-01-03_17.txt)

**Comment by MurdockHM** [comment]
Fixed.
