### ISSUE TITLE
Bring Zack back

### ISSUE THREAD

**Issue by ZackUnfair** [Moe-Team/MysteryOnline#60]
Hello, I'm looking for cute developer girls, preferably experienced ones :wink:

**Comment by Aecheritt** [comment]
https://discord.gg/4DJ9S5

**Comment by ZackUnfair** [comment]
Is that a dating server for devs?

**Comment by Weeping-Cat** [comment]
Yes

**Comment by Aecheritt** [comment]
Yes... a lot of cute developer girls

**Comment by Weeping-Cat** [comment]
A lot of schoolgirls tho be careful with the law

**Comment by Unbancho** [comment]
I get an email for each comment you assholes

**Comment by Aecheritt** [comment]
Oh I'm sorry

**Comment by Aecheritt** [comment]
I will stop now

**Comment by Weeping-Cat** [comment]
There's an unsubscribe button, on the right

**Comment by ZackUnfair** [comment]
No, don't tell him

**Comment by Aecheritt** [comment]
Quick, let's send lots of message before he does

**Comment by ZackUnfair** [comment]
@Unbancho

**Comment by Aecheritt** [comment]
@Unbancho

**Comment by Cascascap** [comment]
Please don't be mean to @Unbancho

**Comment by MurdockHM** [comment]
No
